Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [19]:
import numpy as np

In [3]:
a=np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [5]:
a1=np.reshape(a, (2, 6))
a2=np.reshape(a, (3, 4))
a3=np.reshape(a, (6, 2))
a4=np.reshape(a, (4, 3))
a5=np.reshape(a, (1, 12))
print('Array 2:6', a1, sep='\n')
print('Array 3:4', a2, sep='\n')
print('Array 6:2', a3, sep='\n')
print('Array 4:3', a4, sep='\n')
print('Array 1:12', a5, sep='\n')

Array 2:6
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Array 3:4
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Array 6:2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Array 4:3
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Array 1:12
[[12 13 14 15 16 17 18 19 20 21 22 23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [6]:
a1=np.reshape(a, (2, -1))
a2=np.reshape(a, (3, -1))
a3=np.reshape(a, (6, -1))
a4=np.reshape(a, (-1, 3))
a5=np.reshape(a, (-1, 12))
print('Array 2:6', a1, sep='\n')
print('Array 3:4', a2, sep='\n')
print('Array 6:2', a3, sep='\n')
print('Array 4:3', a4, sep='\n')
print('Array 1:12', a5, sep='\n')

Array 2:6
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Array 3:4
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Array 6:2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Array 4:3
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Array 1:12
[[12 13 14 15 16 17 18 19 20 21 22 23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [7]:
#нет, т.к. каждый элемент будет иметь два индекса - [строка][столбец] - что является признаком двумерного массива

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [8]:
m=np.random.randn(3, 4)
m

array([[-1.48540901, -1.27965427,  1.05001874,  0.47723302],
       [-0.53664919,  0.26307674,  0.16247113, -0.2304608 ],
       [ 1.28676537, -0.03669506,  1.09155505, -0.04939153]])

In [10]:
m2=m.flatten()
print('m size:', m.size)
print('m2 size:', m2.size)

m size: 12
m2 size: 12


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [14]:
a=np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [15]:
b=np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [16]:
# a - одномерный массив, b - двумерный массив

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [21]:
a=np.zeros((2, 2))
print('Array a:', a, sep='\n')

Array a:
[[0. 0.]
 [0. 0.]]


In [22]:
b=np.ones((3, 2))
print('Array b:', b, sep='\n')

Array b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
v=np.vstack((a, b))
print('New array v:', v, sep='\n')
print('Array v size:', v.size)

New array v:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array v size: 10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [33]:
# получается массив от 0 до 11, а не до 12... но если сделать 12 включительно, то ломается reshape

A=np.arange(0, 12).reshape(4, 3)
print('Matrix A:', A, sep='\n')
print('A size:', A.size)

Matrix A:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
A size: 12


In [34]:
At=A.T
print('Matrix At:', At, sep='\n')
print('At size:', At.size)

Matrix At:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
At size: 12


In [42]:
B=np.dot(A, At)
print('Matrix B:', B, sep='\n')
print('B size:', B.size, ', B shape:', B.shape)

Matrix B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
B size: 16 , B shape: (4, 4)


In [36]:
B_inv=np.linalg.inv(B)
print('Matrix B_inv:', B_inv, sep='\n')

LinAlgError: Singular matrix

In [37]:
print('Определитель матрицы В: ', np.linalg.det(B))

Определитель матрицы В:  0.0


In [38]:
# Таким образом обратную матрицу для В вычислить нельзя, т.к. матрица В является квадратной вырожденной (сингулярной)
# и ее определитель равен 0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [61]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [62]:
c=np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

Поменяйте его форму так, чтобы получилась квадратная матрица C

In [63]:
C=np.reshape(c, (4, 4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [64]:
# просто для наглядности
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D

In [65]:
D=np.add(B, np.dot(10, C))
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [67]:
D_inv=np.linalg.inv(D)
print('Определитель матрицы D: ', np.linalg.det(D))
print('Ранг матрицы D: ', np.linalg.matrix_rank(D))
print('Обратная матрица для матрицы D: ')
D_inv

Определитель матрицы D:  -28511999.999999944
Ранг матрицы D:  4
Обратная матрица для матрицы D: 


array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы.

In [70]:
D_inv[D_inv<0]=0
D_inv[D_inv>0]=1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [71]:
# для нагладности

print('Matrix D_inv:', D_inv, sep='\n')
print('Matrix C:', C, sep='\n')
print('Matrix B:', B, sep='\n')

Matrix D_inv:
[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]
Matrix C:
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
Matrix B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [72]:
# жалко, что я такой вариант записи if-else нашла только под конец

E=np.where(D_inv==1, B, C)
print('Matrix E:', E, sep='\n')

Matrix E:
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
